

 // For users  register
POST http://localhost:8000/api/v1/user/register
Content-Type: application/json

{
  "fullname":"Gyanen",
  "email":"gyan12@gmail.com",
  "phoneNumber":"8980",
  "password":"asdf13",
  "role":"student"
    
}




// Login user 
### 
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
"email":"purna123@gmail.com",
"password":"asdf",
"role":"recruiter"

}


//logout user

###
GET  http://localhost:8000/api/v1/user/logout
 

//Update User
###

POST http://localhost:8000/api/v1/user/profile/update
Content-Type: application/json

{
  "fullname":"shankar125",
  "email":"shankar162@gmail.com"
 
    
}




//// Company

# Register Company

###
POST http://localhost:8000/api/v1/company/register
Content-Type: application/json

{
  "companyName":"Shankar And Bikram Ltd"
}

#Get Company
###
GET  http://localhost:8000/api/v1/company/getComp


//Get company by Id

###
GET http://localhost:8000/api/v1/company/getComp/67dee2ae2ca4408d918037ca


//update Company

###
PUT http://localhost:8000/api/v1/company/update/67dee2ae2ca4408d918037ca
Content-Type: application/json


{
  "name":"Shankar Software Company"
}





////Jobs

#####
POST  http://localhost:8000/api/v1/jobs/postJobs
Content-Type: application/json

{
  "title":"Developer",
  "description":"Developer with good working attitude",
  "requirements":"React, Node, MongoDb",
  "salary":"60000",
  "location":"Tasmanina",
  "jobType":"Full Time",
  "experience":2,
  "position":12,
  "companyId":"67dee2ae2ca4408d918037ca"
  




}

///Get all jobs
###

GET http://localhost:8000/api/v1/jobs/getJobs


///Jobs Posted by Admins

###

GET http://localhost:8000/api/v1/jobs/getJobsAdmin





////Individual jobs

###
GET http://localhost:8000/api/v1/jobs/getJobs/67deefad301f39239c35855a



//// Applications= applying jobs

###

GET http://localhost:8000/api/v1/application/apply/67deefad301f39239c35855a

//get applied jobs


### 
GET http://localhost:8000/api/v1/application/get



/// applicants list

###
GET http://localhost:8000/api/v1/application/67deefad301f39239c35855a/applicants



//// status of the jobs applied
###

POST http://localhost:8000/api/v1/application/status/67deefad301f39239c35855a/update
Content-Type: application/json

{
  "status":"accepted"
}