

 // For users  register
POST http://localhost:8000/api/v1/user/register
Content-Type: application/json

{
  "fullname":"Gyanen",
  "email":"gyan12@gmail.com",
  "phoneNumber":"8980",
  "password":"asdf13",
  "role":"student"
    
}




// Login user 
### 
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
"email":"gyan12@gmail.com",
"password":"asdf13",
"role":"student"

}


//logout user

###
GET  http://localhost:8000/api/v1/user/logout
 

//Update User
###

POST http://localhost:8000/api/v1/user/profile/update
Content-Type: application/json

{
  "fullname":"shankar125"
 
    
}




//// Company

# Register Company

###
POST http://localhost:8000/api/v1/company/register
Content-Type: application/json

{
  "companyName":"Shankar Pvt Ltd"
}

#Get Company
###
GET  http://localhost:8000/api/v1/company/getComp


//Get company by Id

###
GET http://localhost:8000/api/v1/company/getComp/675124ec8eda91c0ef7b302a


//update Company

###
PUT http://localhost:8000/api/v1/company/update/675124ec8eda91c0ef7b302a
Content-Type: application/json


{
  "name":"Shankar Software"
}





////Jobs

#####
POST  http://localhost:8000/api/v1/jobs/postJobs
Content-Type: application/json

{
  "title":"Developer",
  "description":"Developer with good working attitude",
  "requirements":"React, Node, MongoDb",
  "salary":"60000",
  "location":"Tasmanina",
  "jobType":"Full Time",
  "experience":2,
  "position":12,
  "companyId":"675124ec8eda91c0ef7b302a"
  




}

///Get all jobs
###

GET http://localhost:8000/api/v1/jobs/getJobs


///Jobs Posted by Admins

###

GET http://localhost:8000/api/v1/jobs/getJobsAdmin





////Individual jobs

###
GET http://localhost:8000/api/v1/jobs/getJobs/67621b4b62f1d23048c9c65e



//// Applications= applying jobs

###

GET http://localhost:8000/api/v1/application/apply/67621b4b62f1d23048c9c65e

//get applied jobs


### 
GET http://localhost:8000/api/v1/application/get



/// applicants list

###
GET http://localhost:8000/api/v1/application/67621b4b62f1d23048c9c65e/applicants



//// status of the jobs applied
###

POST http://localhost:8000/api/v1/application/status/67688e3174c11ddad4997e96/update
Content-Type: application/json

{
  "status":"accepted"
}